
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-helm
spec:
  selector:
    app: web
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerport }}

{{- end }}
