apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $path, $content := .Files.Glob "config/*.conf" }}
  {{ base $path }}: |-
    {{- $content | toString | nindent 4 }}
  {{- end }}

