{{- if .Values.tls.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
data:
  tls.crt: {{ .Files.Get "ssl/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "ssl/server.key" | b64enc }}
{{- end}}
